# Generated by Django 3.0.4 on 2020-03-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_dia_noche'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='inversion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dia',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dia',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='noche',
            name='inversion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='noche',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='noche',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
