# Generated by Django 3.0.4 on 2020-03-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200319_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia',
            name='ganadas',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='perdidas',
        ),
        migrations.RemoveField(
            model_name='noche',
            name='ganadas',
        ),
        migrations.RemoveField(
            model_name='noche',
            name='perdidas',
        ),
        migrations.AddField(
            model_name='dia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noche',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
