# Generated by Django 3.0.4 on 2020-03-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200319_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dia',
            name='divisa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='noche',
            name='divisa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
